version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: frontend
      ports:
        - "3000:3000"  # Make sure this port matches the port Vite runs on
      stdin_open: true
      tty: true
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        - VITE_API_BASE_URL=http://localhost:8000  # Development API URL (change this for production)
        - VITE_HMR=true  # Hot Module Replacement flag (for development)
      command: npm run dev
      depends_on:
        - backend  # Ensure the backend service is available

  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
